// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjv4R5AP8f68cwYgmdKPJV2wvcCvP5BU',
    appId: '1:9181223334:web:31a6edf942b1405b5a1767',
    messagingSenderId: '9181223334',
    projectId: 'comnity-social',
    authDomain: 'comnity-social.firebaseapp.com',
    storageBucket: 'comnity-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH7Jk46lwWeBcph5CATMPaZfh0hu6YzG4',
    appId: '1:9181223334:android:389f54cff41572305a1767',
    messagingSenderId: '9181223334',
    projectId: 'comnity-social',
    storageBucket: 'comnity-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8vOfOZ3ABgCLGL__1sWRTRiYyaa7BPA',
    appId: '1:9181223334:ios:9b3490d19ee601ee5a1767',
    messagingSenderId: '9181223334',
    projectId: 'comnity-social',
    storageBucket: 'comnity-social.appspot.com',
    iosClientId: '9181223334-05c5kc1kjq3se01h6e80ltoesebahjqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comnity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb8vOfOZ3ABgCLGL__1sWRTRiYyaa7BPA',
    appId: '1:9181223334:ios:9b3490d19ee601ee5a1767',
    messagingSenderId: '9181223334',
    projectId: 'comnity-social',
    storageBucket: 'comnity-social.appspot.com',
    iosClientId: '9181223334-05c5kc1kjq3se01h6e80ltoesebahjqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comnity',
  );
}
